### ISSUE TITLE
Check for a proper database format. 

### ISSUE THREAD

**Issue by lmszydlowski** [bioinf-mcb/Metagenomic-DeepFRI#75] opened 2024-03-13 13:33 UTC
Hi there,

After reinstalling a fix today, I encountered another error, this time with multiprocessing (see attached logfile
[log2.txt](https://github.com/bioinf-mcb/Metagenomic-DeepFRI/files/14588396/log2.txt)
)

**Comment by valentynbez** [comment] 2024-03-13 13:43
Could you please paste the command you were running? 
The log has a weird entry, which shows that it tried to align things against Python, which will not work. 
I never encountered it in my tests. 

```[2024-03-13 13:27:04] pipeline.predict_protein_function INFO: Aligning contact maps for 313 proteins against python3```

**Comment by lmszydlowski** [comment] 2024-03-13 14:18
mDeepFRI get-models --output weights/ -v 1.1

mDeepFRI predict-function -i /TomaszLab/metagenomes/JC-0055_annot.faa -d /TomaszLab/Lukasz/foldcomp_database/afdb_swissprot_v4  -w weights/ -o /TomaszLab/Lukasz/mDF_output

**Comment by valentynbez** [comment] 2024-03-13 14:40
I am not able to reproduce the error. 
The most suspicious thing is, however, `python3` listed as a database. That means `python3` was passed as a database to a software. 
Currently, we do not implement checks for the proper format of the database, so the software will break if it is not a FoldComp database.

**Comment by lmszydlowski** [comment] 2024-03-13 14:46
And I'm using foldcomp database from here: https://foldcomp.steineggerlab.workers.dev/afdb_swissprot_v4

**Comment by valentynbez** [comment] 2024-03-13 15:19
Please, create a separate topic for the issues. The two problems mentioned in this track are disconnected and require resolving separately. 
 
This is an unusual error, that propagates downstream. That means that none of the proteins in your datasets had a hit in any of the databases. This is a rare case I had not encountered yet, as a combination of PDB and SwissProt for the reference covers a lot of possible protein sequences. 

This can be resolved by adding at least a single known protein to an input FASTA, while I'll try to fix and test for this particular edge case.

**Comment by lmszydlowski** [comment] 2024-03-13 15:43
Ok I will. Second case
is a proteome of B. subtilis from Genbank, first one is Microbacterium, which was previously annotated, so query proteins are not the issue.

**Comment by lmszydlowski** [comment] 2024-03-13 16:23
[input_fro_log3_GCA_000009045.1_ASM904v1_protein.txt](https://github.com/bioinf-mcb/Metagenomic-DeepFRI/files/14590740/input_fro_log3_GCA_000009045.1_ASM904v1_protein.txt)
[input_for_log2_JC-0055_annot.txt](https://github.com/bioinf-mcb/Metagenomic-DeepFRI/files/14590742/input_for_log2_JC-0055_annot.txt)

**Comment by valentynbez** [comment] 2024-03-13 17:08
I was not able to replicate the errors, however I encountered different ones with contact map alignment, most likely caused by non-uniform PDB records. I will investigate.

**Comment by lmszydlowski** [comment] 2024-03-20 15:32
[log5.txt](https://github.com/bioinf-mcb/Metagenomic-DeepFRI/files/14668873/log5.txt)
Here is another try after reinstalling everything. Line 16 shows an empty input file, even though I've tested multiple .faa files

**Closed** 2024-03-23 18:50 UTC
Labels: enhancement, question
